version: '3.3'
services:
  db:
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_DATABASE: 'chat_db'
      MYSQL_USER: 'aleksandr'
      MYSQL_PASSWORD: '123456789'
      MYSQL_ROOT_PASSWORD: '123456789'
    ports:
      - '3306:3306'
    expose:
      - '3306'